-- =============================================================================
-- TIMELI SUPABASE SQL EDITOR
-- =============================================================================
-- This file contains SQL to be pasted into the Supabase SQL Editor
--
-- INSTRUCTIONS:
-- 1. Go to https://supabase.com/dashboard/project/fbkwuyglamgtihunjamr/sql
-- 2. Copy everything below the "RUN THIS" section
-- 3. Paste into the SQL editor and click "Run"
--
-- WHAT ALREADY EXISTS (DO NOT RECREATE):
-- - profiles table + policies
-- - user_preferences table + policies
-- - fixed_commitments table + policies
-- - update_updated_at() function
-- - life_realms table (if created during onboarding)
-- - user_goals table (if created during onboarding)
--
-- WHAT THIS ADDS:
-- - generated_schedules table (stores weekly schedules)
-- - schedule_completions table (tracks completed/skipped events)
-- - schedule_feedback table (user preferences from chat)
-- - schedule_conversations table (chat history with LLM)
-- - api_usage table (daily API rate limiting for OpenAI fallback)
-- =============================================================================

-- =============================================================================
-- RUN THIS - PASTE EVERYTHING BELOW INTO SUPABASE SQL EDITOR
-- =============================================================================

-- Drop tables if they exist (clean slate for these new tables)
DROP TABLE IF EXISTS public.schedule_conversations CASCADE;
DROP TABLE IF EXISTS public.schedule_feedback CASCADE;
DROP TABLE IF EXISTS public.schedule_completions CASCADE;
DROP TABLE IF EXISTS public.generated_schedules CASCADE;

-- =============================================================================
-- TABLE: generated_schedules
-- =============================================================================
-- Stores weekly schedules generated by the scheduling engine
-- One schedule per user per week

CREATE TABLE public.generated_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  week_start date NOT NULL,
  events jsonb NOT NULL DEFAULT '[]',
  stats jsonb,
  unscheduled_goals jsonb DEFAULT '[]',
  generated_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, week_start)
);

-- =============================================================================
-- TABLE: schedule_completions
-- =============================================================================
-- Tracks task completion history for analytics and learning

CREATE TABLE public.schedule_completions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  schedule_id uuid REFERENCES public.generated_schedules ON DELETE CASCADE,
  event_id text NOT NULL,
  goal_id uuid,
  status text CHECK (status IN ('completed', 'skipped', 'partial')) NOT NULL,
  notes text,
  scheduled_date date,
  scheduled_start_time time,
  completed_at timestamptz DEFAULT now()
);

-- =============================================================================
-- TABLE: schedule_feedback
-- =============================================================================
-- Stores user preferences learned from interactions and chat

CREATE TABLE public.schedule_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  feedback_type text CHECK (feedback_type IN (
    'time_preference',
    'avoid_time',
    'goal_preference',
    'pin_event',
    'block_slot',
    'day_preference',
    'general'
  )) NOT NULL,
  goal_id uuid,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time,
  end_time time,
  preference_value text,
  is_active boolean DEFAULT true,
  source text CHECK (source IN ('chat', 'manual', 'pattern')) DEFAULT 'manual',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- =============================================================================
-- TABLE: schedule_conversations
-- =============================================================================
-- Stores chat history for LLM-powered schedule modifications

CREATE TABLE public.schedule_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  week_start date NOT NULL,
  messages jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, week_start)
);

-- =============================================================================
-- ENABLE ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE public.generated_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_conversations ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- RLS POLICIES: generated_schedules
-- =============================================================================

CREATE POLICY "Users can view own schedules"
  ON public.generated_schedules FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can create own schedules"
  ON public.generated_schedules FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own schedules"
  ON public.generated_schedules FOR UPDATE
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own schedules"
  ON public.generated_schedules FOR DELETE
  USING ((SELECT auth.uid()) = user_id);

-- =============================================================================
-- RLS POLICIES: schedule_completions
-- =============================================================================

CREATE POLICY "Users can view own completions"
  ON public.schedule_completions FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can create own completions"
  ON public.schedule_completions FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own completions"
  ON public.schedule_completions FOR UPDATE
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own completions"
  ON public.schedule_completions FOR DELETE
  USING ((SELECT auth.uid()) = user_id);

-- =============================================================================
-- RLS POLICIES: schedule_feedback
-- =============================================================================

CREATE POLICY "Users can view own feedback"
  ON public.schedule_feedback FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can create own feedback"
  ON public.schedule_feedback FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own feedback"
  ON public.schedule_feedback FOR UPDATE
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own feedback"
  ON public.schedule_feedback FOR DELETE
  USING ((SELECT auth.uid()) = user_id);

-- =============================================================================
-- RLS POLICIES: schedule_conversations
-- =============================================================================

CREATE POLICY "Users can view own conversations"
  ON public.schedule_conversations FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can create own conversations"
  ON public.schedule_conversations FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own conversations"
  ON public.schedule_conversations FOR UPDATE
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own conversations"
  ON public.schedule_conversations FOR DELETE
  USING ((SELECT auth.uid()) = user_id);

-- =============================================================================
-- TRIGGERS: updated_at
-- =============================================================================

CREATE TRIGGER generated_schedules_updated_at
  BEFORE UPDATE ON public.generated_schedules
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER schedule_feedback_updated_at
  BEFORE UPDATE ON public.schedule_feedback
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER schedule_conversations_updated_at
  BEFORE UPDATE ON public.schedule_conversations
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX generated_schedules_user_week_idx
  ON public.generated_schedules(user_id, week_start);

CREATE INDEX schedule_completions_schedule_idx
  ON public.schedule_completions(schedule_id);

CREATE INDEX schedule_completions_user_date_idx
  ON public.schedule_completions(user_id, scheduled_date);

CREATE INDEX schedule_feedback_user_active_idx
  ON public.schedule_feedback(user_id)
  WHERE is_active = true;

CREATE INDEX schedule_conversations_user_week_idx
  ON public.schedule_conversations(user_id, week_start);

-- =============================================================================
-- TABLE: api_usage
-- =============================================================================
-- Tracks per-user daily API usage when using OpenAI fallback.
-- Users get 10 API messages per day, resets at midnight.

DROP TABLE IF EXISTS public.api_usage CASCADE;

CREATE TABLE public.api_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  message_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, date)
);

ALTER TABLE public.api_usage ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own usage"
  ON public.api_usage FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

-- Function for atomic increment (upsert with increment)
CREATE OR REPLACE FUNCTION increment_api_usage(p_user_id UUID, p_date DATE)
RETURNS void AS $$
BEGIN
  INSERT INTO api_usage (user_id, date, message_count)
  VALUES (p_user_id, p_date, 1)
  ON CONFLICT (user_id, date)
  DO UPDATE SET
    message_count = api_usage.message_count + 1,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE INDEX idx_api_usage_user_date ON public.api_usage(user_id, date);

-- =============================================================================
-- SCHEMA RELOAD
-- =============================================================================

NOTIFY pgrst, 'reload schema';

-- =============================================================================
-- SUCCESS!
-- =============================================================================
-- If you see "Success. No rows returned" the migration worked.
--
-- Tables created:
-- - generated_schedules
-- - schedule_completions
-- - schedule_feedback
-- - schedule_conversations
-- - api_usage
--
-- You can verify by running:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
