-- Schedule persistence tables for TimeLi
-- Phase 6: Calendar UI - Plan 04
-- Stores generated schedules, completions, feedback, and conversations

-- =============================================================================
-- GENERATED_SCHEDULES TABLE
-- =============================================================================
-- Stores weekly schedules generated by the scheduling engine
-- One schedule per user per week

CREATE TABLE public.generated_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Week identifier (Monday of the week)
  week_start date NOT NULL,

  -- Schedule data (array of ScheduleEventWithFlexibility)
  events jsonb NOT NULL DEFAULT '[]',

  -- Generation statistics
  stats jsonb,

  -- Any goals that couldn't be scheduled
  unscheduled_goals jsonb DEFAULT '[]',

  -- Timestamps
  generated_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  -- One schedule per user per week
  UNIQUE(user_id, week_start)
);

-- =============================================================================
-- SCHEDULE_COMPLETIONS TABLE
-- =============================================================================
-- Tracks task completion history for analytics and learning

CREATE TABLE public.schedule_completions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Reference to the schedule
  schedule_id uuid REFERENCES public.generated_schedules ON DELETE CASCADE,

  -- Event identification (from the events jsonb)
  event_id text NOT NULL,

  -- Optional goal reference for analytics
  goal_id uuid REFERENCES public.user_goals ON DELETE SET NULL,

  -- Completion status
  status text CHECK (status IN ('completed', 'skipped', 'partial')) NOT NULL,

  -- Optional notes from user
  notes text,

  -- When the event was scheduled for
  scheduled_date date,
  scheduled_start_time time,

  -- Timestamp
  completed_at timestamptz DEFAULT now()
);

-- =============================================================================
-- SCHEDULE_FEEDBACK TABLE
-- =============================================================================
-- Stores user preferences learned from interactions and chat

CREATE TABLE public.schedule_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Type of feedback/preference
  feedback_type text CHECK (feedback_type IN (
    'time_preference',      -- "I prefer mornings for X"
    'avoid_time',           -- "Never schedule after 8pm"
    'goal_preference',      -- "Schedule gym before work"
    'pin_event',            -- "Keep this exact time slot"
    'block_slot',           -- "This time doesn't work this week"
    'day_preference',       -- "No meetings on Fridays"
    'general'               -- Other feedback
  )) NOT NULL,

  -- Optional goal this applies to
  goal_id uuid REFERENCES public.user_goals ON DELETE CASCADE,

  -- Time constraints (optional, depends on type)
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time,
  end_time time,

  -- The actual preference value/description
  preference_value text,

  -- Whether this preference is currently active
  is_active boolean DEFAULT true,

  -- Source of the feedback
  source text CHECK (source IN ('chat', 'manual', 'pattern')) DEFAULT 'manual',

  -- Timestamps
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- =============================================================================
-- SCHEDULE_CONVERSATIONS TABLE
-- =============================================================================
-- Stores chat history for LLM-powered schedule modifications

CREATE TABLE public.schedule_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Week this conversation is about
  week_start date NOT NULL,

  -- Array of message objects: { role: 'user'|'assistant', content: string, timestamp: string }
  messages jsonb NOT NULL DEFAULT '[]',

  -- Timestamps
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  -- One conversation per user per week
  UNIQUE(user_id, week_start)
);

-- =============================================================================
-- ENABLE RLS
-- =============================================================================

ALTER TABLE public.generated_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_conversations ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- RLS POLICIES - GENERATED_SCHEDULES
-- =============================================================================

CREATE POLICY "Users can view own schedules"
  ON public.generated_schedules FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own schedules"
  ON public.generated_schedules FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own schedules"
  ON public.generated_schedules FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own schedules"
  ON public.generated_schedules FOR DELETE
  USING (auth.uid() = user_id);

-- =============================================================================
-- RLS POLICIES - SCHEDULE_COMPLETIONS
-- =============================================================================

CREATE POLICY "Users can view own completions"
  ON public.schedule_completions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own completions"
  ON public.schedule_completions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own completions"
  ON public.schedule_completions FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own completions"
  ON public.schedule_completions FOR DELETE
  USING (auth.uid() = user_id);

-- =============================================================================
-- RLS POLICIES - SCHEDULE_FEEDBACK
-- =============================================================================

CREATE POLICY "Users can view own feedback"
  ON public.schedule_feedback FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own feedback"
  ON public.schedule_feedback FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own feedback"
  ON public.schedule_feedback FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own feedback"
  ON public.schedule_feedback FOR DELETE
  USING (auth.uid() = user_id);

-- =============================================================================
-- RLS POLICIES - SCHEDULE_CONVERSATIONS
-- =============================================================================

CREATE POLICY "Users can view own conversations"
  ON public.schedule_conversations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own conversations"
  ON public.schedule_conversations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own conversations"
  ON public.schedule_conversations FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own conversations"
  ON public.schedule_conversations FOR DELETE
  USING (auth.uid() = user_id);

-- =============================================================================
-- UPDATED_AT TRIGGERS
-- =============================================================================

CREATE TRIGGER generated_schedules_updated_at
  BEFORE UPDATE ON public.generated_schedules
  FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at();

CREATE TRIGGER schedule_feedback_updated_at
  BEFORE UPDATE ON public.schedule_feedback
  FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at();

CREATE TRIGGER schedule_conversations_updated_at
  BEFORE UPDATE ON public.schedule_conversations
  FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at();

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Fast lookup of schedules by user and week
CREATE INDEX generated_schedules_user_week_idx
  ON public.generated_schedules(user_id, week_start);

-- Fast lookup of completions by schedule
CREATE INDEX schedule_completions_schedule_idx
  ON public.schedule_completions(schedule_id);

-- Fast lookup of completions by user and date range
CREATE INDEX schedule_completions_user_date_idx
  ON public.schedule_completions(user_id, scheduled_date);

-- Fast lookup of active feedback by user
CREATE INDEX schedule_feedback_user_active_idx
  ON public.schedule_feedback(user_id)
  WHERE is_active = true;

-- Fast lookup of feedback by goal
CREATE INDEX schedule_feedback_goal_idx
  ON public.schedule_feedback(goal_id)
  WHERE goal_id IS NOT NULL;

-- Fast lookup of conversations by user and week
CREATE INDEX schedule_conversations_user_week_idx
  ON public.schedule_conversations(user_id, week_start);

-- =============================================================================
-- ENHANCEMENTS TO EXISTING TABLES
-- =============================================================================

-- Add realm_id to fixed_commitments for coloring
ALTER TABLE public.fixed_commitments
  ADD COLUMN IF NOT EXISTS realm_id uuid REFERENCES public.life_realms ON DELETE SET NULL;

-- Add time preference fields to user_goals
ALTER TABLE public.user_goals
  ADD COLUMN IF NOT EXISTS preferred_time_window text
    CHECK (preferred_time_window IN ('morning', 'afternoon', 'evening', 'any'))
    DEFAULT 'any';

ALTER TABLE public.user_goals
  ADD COLUMN IF NOT EXISTS excluded_days integer[] DEFAULT '{}';
